### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by wdbasson** [didx-xyz/aries-cloudapi-python#811]
```
"POST /tenant/v1/verifier/accept-request HTTP/1.1" 500 Internal Server Error
```

Occurs in regression tests

ACA-Py logs:
```
TypeError: 'NoneType' object is not subscriptable
	"accum": response_value["accum_to"]["value"]["accum"],
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1056, in get_revoc_reg_delta
	(delta, delta_timestamp) = await ledger.get_revoc_reg_delta(
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/present_proof/indy/pres_exch_handler.py", line 155, in return_presentation
	indy_proof = await indy_handler.return_presentation(
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/present_proof/v1_0/manager.py", line 274, in create_presentation
	) = await presentation_manager.create_presentation(
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/present_proof/v1_0/routes.py", line 854, in presentation_exchange_send_presentation
	result = coro.send(None)
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
	raise self._exception
File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
	future.result()
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
	yield self # This tells Task to wait for completion.
File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
	return await task
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 449, in setup_context
	return await handler(request)
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 384, in check_multitenant_authorization
	return await handler(request)
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 335, in check_token
	return await handler(request)
File "/home/aries/.local/lib/python3.9/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
	return await handler(request)
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 216, in debug_middleware
	return await handler(request)
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 179, in ready_middleware
	Traceback (most recent call last):
=================
Handler error with exception: 'NoneType' object is not subscriptable
Handler error: presentation_exchange_send_presentation
```

**Comment by ff137** [comment]
Fixed with the following: https://github.com/didx-xyz/aries-cloudapi-python/pull/806/commits/217b647c2a29ea67a68e3c1753054bf7ac888748
adds restrictions to which credentials match the proof
